#!/usr/bin/env python3
"""Independent batch/final auditor for v478 Phase-B temporal200."""
from __future__ import annotations
import argparse,ast,hashlib,json,os
from pathlib import Path
from collections import Counter
import h5py,numpy as np

PRE_FORMAT="strict-track2-v478-public-train-temporal200-preregistration-v1"
BATCH_FORMAT="strict-track2-v478-public-train-temporal200-batch-report-v1"
FINAL_FORMAT="strict-track2-v478-public-train-temporal200-generation-report-v1"
BATCH_AUDIT_FORMAT="strict-track2-v478-public-train-temporal200-batch-audit-v1"
FINAL_AUDIT_FORMAT="strict-track2-v478-public-train-temporal200-final-audit-v1"
CONTRACT_SHA="a478b6f8e24d4a2312fcd4f62d294ad681b35ea4c19c1162f7dae7f9748047d1"
UNION_SHA="0d3b1328709ba1b09bb29b1423596e5671fdc37c49215ea4b4f168b9b5fd53cc"
V479_SHA="12ce84ccf3cbf43720f0be0a1e857fcd2c160628a2ab169b006ef8704995b9e3"
VARIANTS=("factual","no_transport","scale_0p4","scale_1p25","reverse_direction_0p4","factual_duplicate");TRANSPORT=VARIANTS[1:5]
KEYS={"episode","dataset_seed","start","variants","prefix_lengths","instruction","pre_future_context_rgb","pre_future_context_state","pre_future_context_pose","pre_future_context_bottle_position","history_actions","future_actions","temporal_rgb","temporal_state","temporal_pose","temporal_bottle_position","context_rgb_sha256","context_state_sha256","executed_prefix_action_sha256","public_factual_target_rgb","public_factual_target_sha256","factual_public_frame_rgb_mae"}

def sha(path):
 h=hashlib.sha256()
 with Path(path).open("rb") as f:
  for b in iter(lambda:f.read(8<<20),b""):h.update(b)
 return h.hexdigest()
def arrsha(x):return hashlib.sha256(np.ascontiguousarray(x).view(np.uint8)).hexdigest()
def atomic(path,obj):
 path=Path(path);tmp=path.with_name(path.name+".tmp")
 if path.exists() or tmp.exists():raise FileExistsError(path)
 with tmp.open("x",encoding="utf-8") as f:json.dump(obj,f,sort_keys=True,indent=2);f.write("\n");f.flush();os.fsync(f.fileno())
 os.replace(tmp,path);fd=os.open(str(path.parent),os.O_RDONLY);os.fsync(fd);os.close(fd)
def support_tree(root):
 root=Path(root).resolve();paths=sorted(p for p in root.rglob("*") if p.is_file() and ".git" not in p.parts and p.suffix.lower() in (".py",".yml",".yaml"));items=[[p.relative_to(root).as_posix(),sha(p)] for p in paths]
 return hashlib.sha256(json.dumps(items,sort_keys=True,separators=(",",":")).encode()).hexdigest(),len(items)
def branches(history,future):
 anchor=history[-1,7:13];delta=future[:,7:13]-anchor;out={}
 for name,scale in (("no_transport",0.),("scale_0p4",.4),("scale_1p25",1.25),("reverse_direction_0p4",-.4)):
  value=future.copy();value[:,7:13]=anchor+scale*delta;out[name]=value
 return {"factual":future.copy(),**out,"factual_duplicate":future.copy()}
def stem(spec):return f"episode{int(spec['episode'])}_start{int(spec['start']):05d}"

def validate_forensics(root,bid):
 base=root/"_forensic_uncommitted"/f"batch_{bid:03d}"
 if not base.exists():return {},{},0
 if any(p.is_symlink() for p in base.rglob("*")):raise RuntimeError(f"forensic symlink {base}")
 q={};f={}
 for attempt in sorted(p for p in base.iterdir() if p.name!="failures"):
  if not attempt.is_dir() or {p.name for p in attempt.iterdir()}!={"quarantine_receipt.json","payload"}:raise RuntimeError(f"forensic quarantine tree {attempt}")
  receipt_path=attempt/"quarantine_receipt.json";receipt=json.loads(receipt_path.read_text());payload=attempt/"payload";source=Path(receipt["source"]);actual={str(p.relative_to(payload)):sha(p) for p in sorted(payload.rglob("*")) if p.is_file()} if payload.is_dir() else {source.name:sha(payload)}
  expected_keys={"format","reason","source","planned_destination","source_files_sha256","payload_name","payload_move_pending_when_receipt_fsynced","deleted_or_reused","effect_or_outcome_conditioned"}
  if set(receipt)!=expected_keys or receipt["format"]!="strict-track2-v478-uncommitted-work-quarantine-v1" or Path(receipt["planned_destination"]).resolve()!=attempt.resolve() or receipt["source_files_sha256"]!=actual or receipt["payload_name"]!="payload" or receipt["deleted_or_reused"] is not False or receipt["effect_or_outcome_conditioned"] is not False:raise RuntimeError(f"forensic receipt {attempt}")
  q[str(receipt_path.relative_to(root))]=sha(receipt_path)
 failures=base/"failures"
 if failures.exists():
  if not failures.is_dir():raise RuntimeError("forensic failures tree")
  for path in sorted(failures.iterdir()):
   if not path.is_file() or path.suffix!=".json":raise RuntimeError(f"forensic failure extra {path}")
   value=json.loads(path.read_text());cleanup=value.get("cleanup",{});expected={"format","passed","batch_id","error","cleanup","cleanup_passed","gpu_peak_mib","attempt_wall_seconds","deleted_or_overwritten","retry_based_on_effect_authorized","full200_collection_authorized","training_authorized","s1_authorized","policy_updates","rl_authorized"}
   if set(value)!=expected or value["format"]!="strict-track2-v478-batch-failure-receipt-v1" or value["passed"] is not False or value["batch_id"]!=bid or value["cleanup_passed"] is not True or set(cleanup)!={"initial_pids","exitcodes","alive_after_cleanup"} or cleanup["alive_after_cleanup"]!=[] or not np.isfinite(float(value["attempt_wall_seconds"])) or float(value["attempt_wall_seconds"])<0 or value["deleted_or_overwritten"] is not False or value["retry_based_on_effect_authorized"] is not False or value["full200_collection_authorized"] is not False or value["training_authorized"] is not False or value["s1_authorized"] is not False or value["policy_updates"]!=0 or value["rl_authorized"] is not False:raise RuntimeError(f"forensic failure receipt {path}")
   f[str(path.relative_to(root))]=sha(path)
 return q,f,sum(p.stat().st_size for p in base.rglob("*") if p.is_file())

def input_closure(a,pre):
 closure=pre["execution_closure"]
 for key,path in (("auditor",Path(__file__).resolve()),("generator",a.generator.resolve()),("collector",a.collector.resolve()),("phase_b_contract",Path(closure["phase_b_contract"]["path"]).resolve()),("endpoint_oracle_union",Path(closure["endpoint_oracle_union"]["path"]).resolve()),("v479_reconciliation_receipt",Path(closure["v479_reconciliation_receipt"]["path"]).resolve()),("selection",a.selection.resolve()),("task_config",a.task_config.resolve()),("resize_source",a.resize_source.resolve())):
  if Path(closure[key]["path"]).resolve()!=path or closure[key]["sha256"]!=sha(path):return False
 contract=json.loads(Path(closure["phase_b_contract"]["path"]).read_text());union=json.loads(Path(closure["endpoint_oracle_union"]["path"]).read_text());v479=json.loads(Path(closure["v479_reconciliation_receipt"]["path"]).read_text());selection=json.loads(a.selection.read_text());selection_receipt=json.loads(Path(closure["selection_receipt"]["path"]).read_text())
 support_digest,support_count=support_tree(a.support_root)
 source=a.collector.read_text();tree=ast.parse(source);forbidden="gen_sparse_reward_data" in source or "save_pcd" in source or any(isinstance(n,ast.Call) and isinstance(n.func,ast.Attribute) and n.func.attr=="check_success" for n in ast.walk(tree))
 base=pre.get("format")==PRE_FORMAT and pre.get("status")=="preregistered_public_train_temporal_collection_authorized" and contract.get("format")=="strict-track2-v478-public-train-temporal200-phase-b-contract-v1" and sha(closure["phase_b_contract"]["path"])==CONTRACT_SHA and union.get("format")=="strict-track2-v478-temporal200-endpoint-oracle-union-v1" and sha(closure["endpoint_oracle_union"]["path"])==UNION_SHA and union.get("rows_digest_sha256")=="3a2aceff3a81dfaa05d8122dbab83181c60071a18570a25a5ae4108463ec04ca" and union.get("counts")=={"batches":10,"contexts_per_batch":20,"total":200,"v461_reused":188,"v478_v479_reconciled":12} and v479.get("passed") is True and sha(closure["v479_reconciliation_receipt"]["path"])==V479_SHA and v479.get("authorization",{}).get("phase_b_temporal_collection_authorized") is True and Path(closure["support_root"]["path"]).resolve()==a.support_root.resolve() and closure["support_root"]["source_config_tree_sha256"]==support_digest and closure["support_root"]["source_config_file_count"]==support_count and Path(pre["dataset_root"]).resolve()==a.dataset.resolve() and str(a.dataset.resolve())=="/root/v478_temporal8_dataset_seed1622_20260824" and len(pre["contexts"])==len(selection.get("contexts",[]))==len(union.get("rows",[]))==200 and pre.get("endpoint_oracle_legacy_alias_semantics")=="generic_bound_endpoint_oracle" and sha(a.selection)==closure["selection"]["sha256"] and sha(closure["selection_receipt"]["path"])==closure["selection_receipt"]["sha256"] and selection_receipt.get("passed") is True and not forbidden
 if not base:return False
 contexts=pre["contexts"]
 for i,(spec,selected,bound) in enumerate(zip(contexts,selection["contexts"],union["rows"])):
  common=("episode","start","batch_id","fold","phase_bin","motion_bin","history_action_sha256","future_action_sha256","branch_action_sha256","source_hdf5","source_hdf5_sha256","source_window","source_window_sha256")
  if any(spec[k]!=selected[k] for k in common) or int(spec["selection_order"])!=i or int(bound["selection_order"])!=i or any(bound[k]!=selected[k] for k in ("episode","start","batch_id","fold","phase_bin","motion_bin","history_action_sha256","future_action_sha256","branch_action_sha256")) or spec["endpoint_oracle"]["path"]!=bound["endpoint_npz"]["path"] or spec["endpoint_oracle"]["sha256"]!=bound["endpoint_npz"]["sha256"] or spec["endpoint_oracle"]["receipt_path"]!=bound["endpoint_receipt"]["path"] or spec["endpoint_oracle"]["receipt_sha256"]!=bound["endpoint_receipt"]["sha256"]:return False
 identities=[(int(x["episode"]),int(x["start"])) for x in contexts];quotas=len(set(identities))==200 and Counter(int(x["fold"]) for x in contexts)==Counter({i:40 for i in range(5)}) and Counter(int(x["phase_bin"]) for x in contexts)==Counter({i:40 for i in range(5)}) and Counter(int(x["motion_bin"]) for x in contexts)==Counter({i:50 for i in range(4)})
 quotas &= all(Counter(int(x["fold"]) for x in contexts if int(x["batch_id"])==b)==Counter({i:4 for i in range(5)}) and Counter(int(x["phase_bin"]) for x in contexts if int(x["batch_id"])==b)==Counter({i:4 for i in range(5)}) and Counter(int(x["motion_bin"]) for x in contexts if int(x["batch_id"])==b)==Counter({i:5 for i in range(4)}) for b in range(10))
 quotas &= all(Counter(int(x["phase_bin"]) for x in contexts if int(x["fold"])==f)==Counter({i:8 for i in range(5)}) and Counter(int(x["motion_bin"]) for x in contexts if int(x["fold"])==f)==Counter({i:10 for i in range(4)}) for f in range(5))
 guards=pre.get("guards",{});return quotas and guards.get("effect_used_for_retry_filter_batch_gate") is False and guards.get("training_authorized") is False and guards.get("s1_authorized") is False and guards.get("zero_update_authorized") is False and guards.get("policy_updates")==0 and guards.get("rl_authorized") is False

def validate(spec,rowdir,pre):
 checks={};npz=rowdir/"temporal.npz";rp=rowdir/"receipt.json";rec=json.loads(rp.read_text())
 checks["atomic_row_tree"]={p.name for p in rowdir.iterdir()}=={"temporal.npz","receipt.json"} and rec.get("npz_sha256")==sha(npz) and rec.get("episode")==int(spec["episode"]) and rec.get("start")==int(spec["start"])
 endpoint=spec["endpoint_oracle"];checks["source_file_closure"]=sha(spec["source_hdf5"])==spec["source_hdf5_sha256"] and sha(spec["source_window"])==spec["source_window_sha256"] and sha(endpoint["path"])==endpoint["sha256"] and sha(endpoint["receipt_path"])==endpoint["receipt_sha256"] and Path(spec["v461_endpoint_npz"]).resolve()==Path(endpoint["path"]).resolve() and spec["v461_endpoint_npz_sha256"]==endpoint["sha256"]
 with h5py.File(spec["source_hdf5"],"r") as h5:raw=np.asarray(h5["joint_action/vector"])
 checks["hdf5_raw_schema"]=raw.dtype==np.float64 and raw.ndim==2 and raw.shape[1]==14 and np.isfinite(raw).all()
 action=raw.astype(np.float32);start=int(spec["start"]);history=action[start:start+4].copy();factual=action[start+4:start+12].copy();formula=branches(history,factual);future=np.stack([formula[n] for n in VARIANTS])
 checks["branch_formula_sha_bounds"]=arrsha(history)==spec["history_action_sha256"] and arrsha(factual)==spec["future_action_sha256"] and all(arrsha(formula[n])==spec["branch_action_sha256"][n] for n in VARIANTS) and np.all(future>=np.asarray(pre["per_dim_action_lower"],np.float32)) and np.all(future<=np.asarray(pre["per_dim_action_upper"],np.float32))
 with np.load(spec["source_window"],allow_pickle=False) as w:wh=np.asarray(w["history_actions"]);wf=np.asarray(w["future_actions"]);wt=np.asarray(w["target_frames"])
 checks["window_alignment"]=wh.shape==(4,14) and wh.dtype==np.float32 and wf.shape==(8,14) and wf.dtype==np.float32 and wt.shape==(8,256,256,3) and wt.dtype==np.uint8 and np.array_equal(wh,history) and np.array_equal(wf,factual)
 with np.load(npz,allow_pickle=False) as z:x={k:np.asarray(z[k]).copy() for k in z.files};checks["npz_exact_keys"]=set(x)==KEYS
 exact=(("pre_future_context_rgb",(6,8,256,256,3),np.uint8),("pre_future_context_state",(6,8,14),np.float32),("pre_future_context_pose",(6,8,16),np.float64),("pre_future_context_bottle_position",(6,8,7),np.float64),("temporal_rgb",(6,8,256,256,3),np.uint8),("temporal_state",(6,8,14),np.float32),("temporal_pose",(6,8,16),np.float64),("temporal_bottle_position",(6,8,7),np.float64),("history_actions",(4,14),np.float32),("future_actions",(6,8,14),np.float32),("public_factual_target_rgb",(8,256,256,3),np.uint8),("factual_public_frame_rgb_mae",(8,),np.float64))
 checks["npz_shape_dtype_finite"]=all(x[k].shape==shape and x[k].dtype==dtype and (dtype==np.uint8 or np.isfinite(x[k]).all()) for k,shape,dtype in exact) and x["episode"].shape==x["dataset_seed"].shape==x["start"].shape==() and x["episode"].dtype==x["dataset_seed"].dtype==x["start"].dtype==np.int64 and x["prefix_lengths"].shape==(8,) and x["prefix_lengths"].dtype==np.int64 and x["variants"].shape==(6,) and x["instruction"].shape==() and x["context_rgb_sha256"].shape==x["context_state_sha256"].shape==x["executed_prefix_action_sha256"].shape==(6,8) and x["public_factual_target_sha256"].shape==(8,)
 checks["stored_identity_actions"]=int(x["episode"])==int(spec["episode"]) and int(x["dataset_seed"])==int(spec["dataset_seed"]) and int(x["start"])==start and str(x["instruction"])==str(spec["instruction"]) and list(x["variants"].astype("U"))==list(VARIANTS) and np.array_equal(x["prefix_lengths"],np.arange(1,9)) and np.array_equal(x["history_actions"],history) and np.array_equal(x["future_actions"],future) and np.array_equal(x["public_factual_target_rgb"],wt)
 checks["stored_hashes"]=all(str(x["executed_prefix_action_sha256"][i,k-1])==arrsha(future[i,:k]) and str(x["context_rgb_sha256"][i,k-1])==arrsha(x["pre_future_context_rgb"][i,k-1]) and str(x["context_state_sha256"][i,k-1])==arrsha(x["pre_future_context_state"][i,k-1]) for i in range(6) for k in range(1,9)) and all(str(x["public_factual_target_sha256"][k])==arrsha(wt[k]) for k in range(8))
 flat=lambda key:x[key].reshape(48,*x[key].shape[2:]);checks["same_context_48way"]=all(np.array_equal(flat(key)[0],flat(key)[i]) for key in ("pre_future_context_rgb","pre_future_context_state","pre_future_context_pose","pre_future_context_bottle_position") for i in range(1,48))
 with np.load(endpoint["path"],allow_pickle=False) as oz:o={k:np.asarray(oz[k]).copy() for k in ("branch_context_rgb","branch_context_state","branch_context_pose","branch_context_bottle_position","endpoint_rgb","endpoint_state","endpoint_bottle_position")}
 eq=lambda key,okey:all(np.array_equal(x[key][i],np.repeat(o[okey][i,None],8,axis=0)) for i in range(6));checks["generic_endpoint_oracle"]=eq("pre_future_context_rgb","branch_context_rgb") and eq("pre_future_context_state","branch_context_state") and eq("pre_future_context_pose","branch_context_pose") and eq("pre_future_context_bottle_position","branch_context_bottle_position") and np.array_equal(x["temporal_rgb"][:,-1],o["endpoint_rgb"]) and np.array_equal(x["temporal_state"][:,-1],o["endpoint_state"]) and np.array_equal(x["temporal_bottle_position"][:,-1],o["endpoint_bottle_position"])
 checks["factual_duplicate_exact"]=all(np.array_equal(x[key][0],x[key][5]) for key in ("temporal_rgb","temporal_state","temporal_pose","temporal_bottle_position"))
 public=np.asarray([np.abs(x["temporal_rgb"][0,k].astype(np.float32)-wt[k].astype(np.float32)).mean() for k in range(8)],np.float64);checks["public_diagnostic_exact"]=np.array_equal(public,x["factual_public_frame_rgb_mae"])
 effects={}
 for i,n in enumerate(TRANSPORT,1):
  rgb=[float(np.abs(x["temporal_rgb"][i,k].astype(np.float32)-x["temporal_rgb"][0,k].astype(np.float32)).mean()) for k in range(8)];state=[float(np.linalg.norm(x["temporal_state"][i,k]-x["temporal_state"][0,k])) for k in range(8)];bottle=[float(np.linalg.norm(x["temporal_bottle_position"][i,k]-x["temporal_bottle_position"][0,k])) for k in range(8)];effective=[rgb[k]>=1. and (state[k]>=.01 or bottle[k]>=.005) for k in range(8)];effects[n]={"rgb_mae":rgb,"state_l2":state,"bottle_position_l2":bottle,"effective_prefixes":effective,"effective_prefix_count":sum(effective),"passed":sum(effective)>=2}
 required=("context_48way_bitexact","context_v461_oracle_bitexact","k8_v461_rgb_state_bottle_bitexact","executed_prefix_actions_exact","action_bounds_passed","factual_duplicate_temporal_rgb_state_pose_bottle_bitexact","all_fixed_rows_branches_retained","temporal_real_simulator_frames","cumulative_prefix_single_chunk_per_frame")
 checks["receipt_semantics_integrity_only"]=all(rec.get(k) is True for k in required) and rec.get("task_reward_success_done_outcome_consumed") is False and rec.get("effects")==effects
 return all(checks.values()),checks,effects,sha(npz)

def audit_batch(a,pre,bid):
 specs=[x for x in pre["contexts"] if int(x["batch_id"])==bid];batch=a.dataset/f"batch_{bid:03d}";report=json.loads((batch/"batch_report.json").read_text());expected=[stem(x) for x in specs]
 rows=[];counts={n:0 for n in TRANSPORT};contexts3=0
 for spec in specs:
  ok,checks,effects,nsha=validate(spec,batch/"rows"/stem(spec),pre);rows.append({"episode":int(spec["episode"]),"start":int(spec["start"]),"passed":ok,"checks":checks,"npz_sha256":nsha,"effects":{n:bool(effects[n]["passed"]) for n in TRANSPORT}});contexts3+=int(sum(effects[n]["passed"] for n in TRANSPORT)>=3)
  for n in TRANSPORT:counts[n]+=int(effects[n]["passed"])
 declared=[(int(x["episode"]),int(x["start"]),x["npz_sha256"]) for x in report.get("rows",[])];actual=[(x["episode"],x["start"],x["npz_sha256"]) for x in rows]
 storage_ok=True
 for key in ("storage_pre","storage_post"):
  value=report.get(key,{});expected_required=max(6442450944 if key=="storage_pre" and int(value.get("remaining_rows",-1))==200 else 0,4294967296+int(value.get("remaining_rows",-1))*11000000+268435456)
  storage_ok &= value.get("remaining_worst_case_bytes")==int(value.get("remaining_rows",-1))*11000000 and value.get("atomic_quarantine_reserve_bytes")==268435456 and value.get("required_root_free_bytes")==expected_required and int(value.get("root_free_bytes",-1))>=expected_required and int(value.get("registry_free_bytes",-1))>=3221225472 and value.get("required_registry_free_bytes")==3221225472
 q,f,forensic_bytes=validate_forensics(a.dataset,bid);row_bytes=sum(p.stat().st_size for p in (batch/"rows").rglob("*") if p.is_file());failure_wall=sum(float(json.loads((a.dataset/rel).read_text()).get("attempt_wall_seconds",0)) for rel in f);attempt=float(report.get("attempt_wall_seconds",-1));cumulative=float(report.get("cumulative_attempt_wall_seconds",-1));peak=int(report.get("gpu_peak_mib",-1));expected_checks={"exact20":len(specs)==len(rows)==20,"all_rows_integrity":all(x["passed"] for x in rows),"cumulative_attempt_wall_le_5400":cumulative<=5400,"gpu_le_24576":0<=peak<=24576,"output_plus_forensic_within_contract":row_bytes+forensic_bytes<=400000000,"storage_post_and_remaining_gate":bool(storage_ok)};expected_guards={"all_selected_rows_branches_frames_retained":True,"technical_effect_filters_rows":False,"technical_effect_gates_batch":False,"task_reward_success_outcome_consumed":False,"training_authorized":False,"s1_authorized":False,"policy_updates":0,"rl_authorized":False};expected_keys={"format","passed","batch_id","checks","rows","transport_effect_context_counts_diagnostic","contexts_at_least_three_of_four_effects_diagnostic","effect_used_for_batch_pass_retry_filter","committed_rows_pre","valid_partial_rows_pre","remaining_rows_pre","remaining_rows_post","attempt_wall_seconds","prior_failed_attempt_wall_seconds","cumulative_attempt_wall_seconds","gpu_peak_mib","row_output_bytes","forensic_output_bytes","total_attempt_output_bytes","storage_pre","storage_post","quarantine_receipts_sha256","failure_receipts_sha256","guards"};counts_exact=report.get("committed_rows_pre")==bid*20 and 0<=int(report.get("valid_partial_rows_pre",-1))<=20 and report.get("remaining_rows_pre")==200-bid*20-report.get("valid_partial_rows_pre") and report.get("remaining_rows_post")==200-(bid+1)*20 and report.get("storage_pre",{}).get("remaining_rows")==report.get("remaining_rows_pre") and report.get("storage_post",{}).get("remaining_rows")==report.get("remaining_rows_post");resource_exact=set(report)==expected_keys and counts_exact and report.get("checks")==expected_checks and report.get("guards")==expected_guards and report.get("row_output_bytes")==row_bytes and report.get("forensic_output_bytes")==forensic_bytes and report.get("total_attempt_output_bytes")==row_bytes+forensic_bytes and report.get("quarantine_receipts_sha256")==q and report.get("failure_receipts_sha256")==f and report.get("prior_failed_attempt_wall_seconds")==failure_wall and cumulative==attempt+failure_wall
 checks={"input_closure":input_closure(a,pre),"exact20_selection_order":len(specs)==20 and actual==declared,"batch_exact_tree":{p.name for p in batch.iterdir()}=={"rows","batch_report.json"} and set(p.name for p in (batch/"rows").iterdir())==set(expected),"all_rows_independently_valid":all(x["passed"] for x in rows),"batch_report_integrity":report.get("format")==BATCH_FORMAT and report.get("passed") is True and report.get("batch_id")==bid and report.get("effect_used_for_batch_pass_retry_filter") is False and resource_exact,"storage_formula_and_historic_gates":bool(storage_ok),"diagnostic_recomputed_but_not_gate":report.get("transport_effect_context_counts_diagnostic")==counts and report.get("contexts_at_least_three_of_four_effects_diagnostic")==contexts3}
 passed=all(checks.values());return {"format":BATCH_AUDIT_FORMAT,"passed":passed,"batch_id":bid,"checks":checks,"rows":rows,"transport_effect_context_counts_diagnostic":counts,"contexts_at_least_three_of_four_effects_diagnostic":contexts3,"batch_report_sha256":sha(batch/"batch_report.json"),"authorization":{"next_batch_resume_authorized":passed,"technical_effect_used_for_authorization":False,"training_authorized":False,"s1_authorized":False,"zero_update_authorized":False,"policy_updates":0,"rl_authorized":False}}

def main():
 ap=argparse.ArgumentParser()
 for n in ("preregistration","selection","collector","generator","dataset","support-root","task-config","resize-source","output","batch-audit-dir"):ap.add_argument("--"+n,type=Path)
 mode=ap.add_mutually_exclusive_group(required=True);mode.add_argument("--batch-id",type=int);mode.add_argument("--finalize",action="store_true")
 a=ap.parse_args();required=("preregistration","selection","collector","generator","dataset","support_root","task_config","resize_source","output")
 if any(getattr(a,n) is None for n in required):raise RuntimeError("missing required audit argument")
 pre=json.loads(a.preregistration.read_text())
 if a.batch_id is not None:
  if not 0<=a.batch_id<10:raise RuntimeError("batch id")
  result=audit_batch(a,pre,a.batch_id);atomic(a.output,result);return 0 if result["passed"] else 3
 if a.batch_audit_dir is None:raise RuntimeError("final audit requires batch-audit-dir")
 audits=[]
 for bid in range(10):
  path=a.batch_audit_dir/f"batch_{bid:03d}_audit.json";stored=json.loads(path.read_text());fresh=audit_batch(a,pre,bid)
  if stored!=fresh or stored.get("passed") is not True:raise RuntimeError(f"batch audit drift {bid}")
  audits.append(fresh)
 report_path=a.dataset/"generation_report.json";report=json.loads(report_path.read_text());counts={n:sum(x["transport_effect_context_counts_diagnostic"][n] for x in audits) for n in TRANSPORT};contexts3=sum(x["contexts_at_least_three_of_four_effects_diagnostic"] for x in audits);top={p.name for p in a.dataset.iterdir()};tree_ok=top.issubset({*(f"batch_{b:03d}" for b in range(10)),"_forensic_uncommitted","generation_report.json"}) and all((a.dataset/f"batch_{b:03d}").is_dir() for b in range(10)) and not any(a.dataset.glob("batch_*.partial"));output_bytes=sum(p.stat().st_size for p in a.dataset.rglob("*") if p.is_file());pre_report_bytes=output_bytes-report_path.stat().st_size;wall=sum(json.loads((a.dataset/f"batch_{b:03d}"/"batch_report.json").read_text())["cumulative_attempt_wall_seconds"] for b in range(10));expected_integrity_checks={"ten_batches":True,"exact200":True,"all_batch_integrity_passed":all(x["passed"] for x in audits),"whole_cumulative_attempt_wall_le_43200":wall<=43200,"total_output_including_forensics_le_3221225472":pre_report_bytes<=3221225472,"no_partial_batches":not any(a.dataset.glob("batch_*.partial")),"no_effect_used_for_batch_pass_retry_filter":True};expected_effect_checks={"all_200_contexts_have_at_least_three_of_four_transport_effects":contexts3==200,"each_named_transport_effect_contexts_at_least_150":all(counts[n]>=150 for n in TRANSPORT),"computed_after_all200_integrity_complete":all(expected_integrity_checks.values()),"never_used_for_batch_stop_resume_retry_filter":True};integrity=report.get("collection_integrity_passed") is True and report.get("integrity_checks")==expected_integrity_checks and all(expected_integrity_checks.values());effect=report.get("technical_effect_diagnostic_qualification_passed") is True and report.get("technical_effect_diagnostic_checks")==expected_effect_checks and all(expected_effect_checks.values())
 actual_batch_sha={f"batch_{b:03d}":sha(a.dataset/f"batch_{b:03d}"/"batch_report.json") for b in range(10)};expected_guards={"complete_dataset_retained_on_diagnostic_failure":True,"retry_authorized_on_diagnostic_failure":False,"temporal_model_design_authorized_if_pass":True,"training_authorized":False,"s1_authorized":False,"zero_update_authorized":False,"policy_updates":0,"rl_authorized":False};expected_report_keys={"format","passed","collection_integrity_passed","technical_effect_diagnostic_qualification_passed","integrity_checks","technical_effect_diagnostic_checks","batch_reports_sha256","transport_effect_context_counts_diagnostic","contexts_at_least_three_of_four_effects_diagnostic","cumulative_attempt_wall_seconds","output_bytes_including_forensics","preregistration_sha256","generator_sha256","collector_sha256","guards"}
 checks={"input_closure":input_closure(a,pre),"ten_independent_batch_audits":all(x["passed"] for x in audits),"exact200_9600_replays":sum(len(x["rows"]) for x in audits)==200 and 200*6*8==9600,"collection_integrity_passed":integrity,"technical_effect_whole200_only":effect and report.get("transport_effect_context_counts_diagnostic")==counts and report.get("contexts_at_least_three_of_four_effects_diagnostic")==contexts3,"generation_report_exact":set(report)==expected_report_keys and report.get("format")==FINAL_FORMAT and report.get("passed") is True and report.get("preregistration_sha256")==sha(a.preregistration) and report.get("generator_sha256")==sha(a.generator) and report.get("collector_sha256")==sha(a.collector) and report.get("batch_reports_sha256")==actual_batch_sha and report.get("cumulative_attempt_wall_seconds")==wall and report.get("output_bytes_including_forensics")==pre_report_bytes and report.get("guards")==expected_guards,"dataset_tree_no_partial_or_extra":tree_ok,"whole_output_cap":output_bytes<=3221225472,"no_training_s1_rl":report.get("guards")==expected_guards}
 passed=all(checks.values());result={"format":FINAL_AUDIT_FORMAT,"passed":passed,"collection_integrity_passed":integrity,"technical_effect_diagnostic_qualification_passed":effect,"checks":checks,"batch_audits_sha256":{f"batch_{b:03d}":sha(a.batch_audit_dir/f"batch_{b:03d}_audit.json") for b in range(10)},"generation_report_sha256":sha(report_path),"transport_effect_context_counts_diagnostic":counts,"contexts_at_least_three_of_four_effects_diagnostic":contexts3,"output_bytes_including_forensics":output_bytes,"authorization":{"temporal_model_design_authorized":passed,"training_authorized":False,"s1_authorized":False,"zero_update_authorized":False,"policy_updates":0,"rl_authorized":False}}
 atomic(a.output,result);return 0 if passed else 3
if __name__=="__main__":raise SystemExit(main())
