#!/usr/bin/env python3
"""Audit completeness, branch execution and same-context invariants of v449 pilot."""
from __future__ import annotations
import argparse, ast, hashlib, json
from pathlib import Path
import h5py
import numpy as np

VARIANTS=("factual","open","static_transport","reverse_transport","hold_all","factual_duplicate")
def digest(x): return hashlib.sha256(np.ascontiguousarray(x).view(np.uint8)).hexdigest()
def file_digest(path):
 h=hashlib.sha256()
 with Path(path).open("rb") as handle:
  for block in iter(lambda:handle.read(8<<20),b""): h.update(block)
 return h.hexdigest()
def main()->int:
 p=argparse.ArgumentParser()
 for n in ("preregistration","dataset-dir","generator","output"): p.add_argument(f"--{n}",type=Path,required=True)
 a=p.parse_args(); pre=json.loads(a.preregistration.read_text()); rep=json.loads((a.dataset_dir/"generation_report.json").read_text()); source=a.generator.read_text(); tree=ast.parse(source); files=sorted(a.dataset_dir.glob("episode*_start*.npz")); row_checks=[]
 specs={(int(x["episode"]),int(x["start"])):x for x in pre["public_train"]["contexts"]}; expected_contexts=set(specs); observed=set()
 for path in files:
  with np.load(path,allow_pickle=False) as z:
   episode=int(z["episode"]); start=int(z["start"]); observed.add((episode,start)); contexts=z["branch_context_frames"]; states=z["branch_context_state"]; poses=z["branch_context_pose"]; context_bottles=z["branch_context_bottle_position"]; history=z["history_actions"]; futures=z["future_actions"]; targets=z["target_frames"]; final_state=z["branch_final_state"]; final_bottle=z["branch_final_bottle_position"]; variants=list(map(str,z["variants"])); context_hash=list(map(str,z["context_sha256"])); state_hash=list(map(str,z["state_sha256"])); pose_hash=list(map(str,z["pose_sha256"])); bottle_hash=list(map(str,z["bottle_position_sha256"])); executed=list(map(str,z["executed_action_sha256"])); keys=set(z.files)
   spec=specs[(episode,start)]
   with np.load(spec["source_window"],allow_pickle=False) as source: public_target=source["target_frames"].astype(np.uint8); public_history=source["history_actions"].astype(np.float32); public_future=source["future_actions"].astype(np.float32)
   with h5py.File(spec["source_hdf5"],"r") as h5: public_actions=np.asarray(h5["joint_action/vector"],dtype=np.float32)
   factual=futures[0].copy(); expected_branches=np.stack((factual,np.concatenate((factual[:,:13],np.ones((8,1),dtype=np.float32)),axis=1),factual.copy(),factual.copy(),np.repeat(history[-1:],8,axis=0),factual.copy())); expected_branches[2,:,7:13]=history[-1,7:13]; expected_branches[3,:,7:13]=factual[::-1,7:13]
   fidelity=float(np.abs(targets[0].astype(np.float32)-public_target.astype(np.float32)).mean()); duplicate=float(np.abs(targets[0].astype(np.float32)-targets[5].astype(np.float32)).mean()); context_mae=max(float(np.abs(x.astype(np.float32)-contexts[0].astype(np.float32)).mean()) for x in contexts[1:]); qpos_max=max(float(np.abs(x-states[0]).max()) for x in states[1:]); pose_max=max(float(np.abs(x-poses[0]).max()) for x in poses[1:]); bottle_max=max(float(np.abs(x-context_bottles[0]).max()) for x in context_bottles[1:]); context_exact=all(np.array_equal(contexts[0],x) and np.array_equal(states[0],states[i]) and np.array_equal(poses[0],poses[i]) and np.array_equal(context_bottles[0],context_bottles[i]) for i,x in enumerate(contexts[1:],1)); context_pass=context_exact or (context_mae<=.25 and qpos_max<=1e-5 and pose_max<=1e-5 and bottle_max<=1e-5); noise=max(1.,5.*duplicate); causal=[]
   for index in range(1,5):
    rgb=float(np.abs(targets[index,-1].astype(np.float32)-targets[0,-1].astype(np.float32)).mean()); qpos=float(np.linalg.norm(final_state[index]-final_state[0])); bottle=float(np.linalg.norm(final_bottle[index]-final_bottle[0])); causal.append(rgb>=noise and (qpos>=.01 or bottle>=.005))
   checks={"variants":variants==list(VARIANTS),"shapes_dtypes":contexts.shape[:2]==(6,5) and contexts.dtype==np.uint8 and futures.shape==(6,8,14) and futures.dtype==np.float32 and targets.shape[:2]==(6,8) and targets.dtype==np.uint8 and history.shape==(4,14) and history.dtype==np.float32 and states.shape[0]==poses.shape[0]==context_bottles.shape[0]==6,"source_closure":file_digest(spec["source_hdf5"])==spec["source_hdf5_sha256"] and file_digest(spec["source_window"])==spec["source_window_sha256"],"finite_public_bounds":start>=0 and start+12<=len(public_actions) and np.isfinite(history).all() and np.isfinite(futures).all() and float(np.abs(futures).max())<=10. and float(futures[:,:,6].min())>=-1e-6 and float(futures[:,:,13].min())>=-1e-6 and float(futures[:,:,6].max())<=1.000001 and float(futures[:,:,13].max())<=1.000001,"source_index_binding":np.array_equal(history,public_actions[start:start+4]) and np.array_equal(factual,public_actions[start+4:start+12]) and np.array_equal(history,public_history) and np.array_equal(factual,public_future),"branch_formula_exact":np.array_equal(futures,expected_branches),"context_equivalent":context_pass and context_hash==[digest(x) for x in contexts] and state_hash==[digest(x) for x in states] and pose_hash==[digest(x) for x in poses] and bottle_hash==[digest(x) for x in context_bottles],"executed_action_binding":executed==[digest(x) for x in futures],"factual_duplicate":duplicate<=.5,"factual_replay_fidelity":digest(public_target)==str(z["public_factual_target_sha256"]) and abs(fidelity-float(z["factual_replay_public_target_rgb_mae"]))<1e-9 and fidelity<=8.,"causal_counterfactuals":sum(causal)>=2,"no_outcome_fields":not keys.intersection({"reward","success","done","termination","truncation","outcome","policy_action"})}
   row_checks.append({"episode":episode,"start":start,"passed_noncausal":all(v for k,v in checks.items() if k!="causal_counterfactuals"),"causal_passed":checks["causal_counterfactuals"],"checks":checks})
 calls=[node.func.attr for node in ast.walk(tree) if isinstance(node,ast.Call) and isinstance(node.func,ast.Attribute)]
 imports=[node.module or "" for node in ast.walk(tree) if isinstance(node,ast.ImportFrom)]+[alias.name for node in ast.walk(tree) if isinstance(node,ast.Import) for alias in node.names]
 guards=rep.get("guards",{})
 pointcloud_outputs=sorted(str(path.relative_to(a.dataset_dir)) for path in a.dataset_dir.rglob("*") if path.is_file() and path.suffix.lower() in {".pcd",".ply"})
 attribute_names={node.attr for node in ast.walk(tree) if isinstance(node,ast.Attribute)}
 checks={"prereg_format":pre.get("format")=="strict-track2-v449-paired-intervention-pilot-preregistration-v1","generation_report_pass":rep.get("passed") is True and not rep.get("technical_failures"),"exact_four_contexts_six_branches":len(files)==4 and observed==expected_contexts and len(row_checks)==4,"four_context_noncausal_hard_gates":all(r["passed_noncausal"] for r in row_checks),"causal_three_of_four":sum(r["causal_passed"] for r in row_checks)>=3,"public_train_only":set(e for e,_ in observed)==set(pre["public_train"]["episodes"]) and not set(e for e,_ in observed).intersection(pre["public_train"]["validation_excluded"]),"mplib_no_curobo":guards.get("planner_backend")=="mplib" and guards.get("curobo_used") is False,"open3d_rgb_only_stub":guards.get("open3d_stub_rgb_only") is True and guards.get("pointcloud_calls")==0 and "ensure_open3d_importable" in source and "__v449_rgb_only_stub__" in source and "save_pcd" not in source and not attribute_names.intersection({"write_point_cloud","draw_geometries","save_pcd"}) and not pointcloud_outputs and rep.get("pointcloud_files")==[] and len(rep.get("rows",[]))==4 and all(row.get("open3d_import_mode")=="rgb_only_stub" for row in rep.get("rows",[])),"fixed_step_interface":calls.count("step")>=3 and "predict" not in calls,"no_reward_model_import":not any("reward" in x.lower() for x in imports),"no_outcome_filter_source":not any(token in source for token in ("check_success()","if reward","if done","if success","if outcome")),"no_policy_training":not any(token in source.lower() for token in ("optimizer","backward(","policy_action","behavior cloning","mpc")),"resource_output_contract":rep.get("output_bytes",2**60)<=16777216 and rep.get("gpu_peak_mib",2**60)<=8192 and rep.get("wall_seconds",2**60)<=1200 and guards.get("retry")==0 and guards.get("context_workers")==2 and guards.get("branches_serial") is True and guards.get("context_timeout_seconds")==300 and guards.get("fixed_future_frames")==8 and guards.get("success_check_forced_false") is True and guards.get("reward_success_done_consumed") is False and guards.get("technical_intervention_effect_gate") is True and guards.get("task_outcome_or_reward_selection") is False and guards.get("all_fixed_rows_branches_retained") is True}
 passed=all(v is True for v in checks.values()); audit={"format":"strict-track2-v449-paired-intervention-pilot-audit-v1","passed":passed,"checks":checks,"rows":row_checks,"guards":{"open3d_stub_rgb_only":True,"pointcloud_calls":0,"dataset_only":True,"policy_bc_authorized":False,"policy_updates":0,"s1_authorized":False,"rl_authorized":False,"real_submission":False}}
 a.output.write_text(json.dumps(audit,indent=2)+"\n"); print(json.dumps(audit,indent=2)); return 0 if passed else 2
if __name__=="__main__": raise SystemExit(main())
